### ISSUE TITLE
error in starting the server

### ISSUE THREAD

**Issue by iamBalaji** [FSFTN/librenote#1]
this is the error i got while starting the meteor server...
![selection_007](https://cloud.githubusercontent.com/assets/6650280/8819855/b5f9441e-306d-11e5-9ce3-5511d9f11dac.png)

**Comment by rajanand02** [comment]
you must set the environment variables and you must have mongodb installed in your computer. use `start` shell script file to start the meteor app and moreover you need `settings.json` file under `config` directory which contains the github clientId and secret key. here is an example `config/settings.json` file.

```
{
  "public":{
  },
  "development":{
    "githubClientId": "xxxxxx",
    "githubSecretKey": "yyyy"
  },
  "production":{
  }
}
```
The `settings.json` file has all the private keys so i did not add it to the repo.. check `.gitignore` file for more information.

**Comment by rajanand02** [comment]
update the wiki. please refer [guide](https://github.com/FSFTN/librenote/wiki/Guides)
