### ISSUE TITLE
"search note" fetches notes from all signed up users.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [FSFTN/librenote#6]
When searched for using a keyword, Notes from all registered users containing the keyword is fetched and displayed to the user who is searching.

**Comment by rajanand02** [comment]
Woah..this is a major bug. Not checking for current user on mongo full text search. Thanks for poiting out.

**Comment by rajanand02** [comment]
just patched a quick fix. Working on a proper update.

**Comment by rajanand02** [comment]
@arjunmayilvaganan The issue has been fixed. I am closing the thread now. Please verify and re-open if the issue persists.

**Comment by arjunmayilvaganan** [comment]
Thanks for looking into this. Works fine now!
