### ISSUE TITLE
Changing text formatting

### ISSUE THREAD

**Issue by arjunmayilvaganan** [FSFTN/Librenote#8]
Actually typed out note:
![before](https://cloud.githubusercontent.com/assets/6371303/10884570/af93849a-819e-11e5-8b2c-9387ddc15740.png)

After saving and refreshing:
![after](https://cloud.githubusercontent.com/assets/6371303/10884643/2237d60e-819f-11e5-88d5-9cd85530f463.png)

Unable to guess the reason and not sure how to describe the issue and hence attaching screenshots.

**Comment by mohsalsaleem** [comment]
Is it showing like that only in the pop up or also while listing the notes?

**Comment by arjunmayilvaganan** [comment]
![screen shot 2015-11-02 at 8 49 46 pm](https://cloud.githubusercontent.com/assets/6371303/10885466/5b70ef74-81a3-11e5-87a8-15a805da709e.png)
Also during during listing.

**Comment by rajanand02** [comment]
yeah even I noticed this today only. I can work on this over the weekend and fix it but PRs are most welcome. @arjunmayilvaganan @mohsalsaleem I can help you guys with fixing the bug

**Comment by rajanand02** [comment]
@arjunmayilvaganan @mohsalsaleem the content is being saved as plain text that is the reason. we just need to save it as html content.

**Comment by rajanand02** [comment]
@arjunmayilvaganan  I guess I fixed it..please do a quick check and close the thread if the problem is resolved.

**Comment by arjunmayilvaganan** [comment]
Yes, Now works fine.
